-- This migration is intentionally left as a marker.
-- SQLite deploys on Render can have these columns already present from a previous partial sync.
-- The backend startup compatibility check adds any missing columns safely.
